import { Product, FAQ, Testimonial, TeamMember, CraftingStep } from './types';

export const products: Product[] = [
  {
    id: 'urn-01',
    slug: 'hand-painted-ceramic-urn-01',
    name: 'Hand-Painted Ceramic Memorial Urn',
    category: 'urns',
    tagline: 'A quiet vessel for eternal companionship',
    description: 'Each urn is hand-painted by our artisans using natural mineral pigments, creating a one-of-a-kind resting place that reflects the unique spirit of your beloved companion.',
    longDescription: 'Our signature hand-painted urns are crafted from premium ceramic clay, shaped and fired over 72 hours. Each piece undergoes a meticulous 12-step process, including three rounds of hand-glazing and kiln-firing. The surface is adorned with subtle botanical motifs inspired by the Japanese tradition of kintsugi — the art of golden repair — symbolizing that the beauty of life persists even through loss. No two urns are ever identical.',
    price: 68,
    materials: ['Premium ceramic clay', 'Natural mineral pigments', 'Gold leaf accents', 'Velvet-lined interior'],
    dimensions: '18cm x 12cm x 12cm',
    craftingTime: '10-14 business days',
    features: [
      'Hand-painted botanical design',
      'Gold leaf accent details',
      'Velvet-lined interior',
      'Airtight seal',
      'Personalized name engraving available',
      'Gift packaging included',
    ],
    images: ['/images/urn-01.webp'],
    featured: true,
    isNew: false,
  },
  {
    id: 'urn-02',
    slug: 'minimalist-walnut-wood-urn',
    name: 'Minimalist Walnut Wood Urn',
    category: 'urns',
    tagline: 'Quiet elegance in warm walnut',
    description: 'A minimalist tribute carved from a single piece of sustainably sourced walnut wood, finished with organic beeswax.',
    longDescription: 'Each urn is carved from a single block of North American black walnut, selected for its deep, warm grain patterns. The minimalist silhouette is hand-sanded through eight progressive grits before receiving a natural beeswax finish. The result is a piece that feels as warm and grounding as the memories it holds. The wood grain ensures every urn is unique — much like the companion it honors.',
    price: 82,
    materials: ['Solid black walnut', 'Organic beeswax finish', 'Suede-lined interior', 'Brass nameplate'],
    dimensions: '20cm x 14cm x 14cm',
    craftingTime: '14-21 business days',
    features: [
      'Single-piece walnut construction',
      'Natural beeswax finish',
      'Engraved brass nameplate',
      'Suede interior lining',
      'Magnetic closure',
      'Complimentary memorial card',
    ],
    images: ['/images/urn-02.jpg'],
    featured: true,
    isNew: true,
  },
  {
    id: 'felt-01',
    slug: 'custom-wool-felt-replica',
    name: 'Custom Wool Felt Portrait Replica',
    category: 'felt-replicas',
    tagline: 'Your companion, reimagined in wool and love',
    description: 'Our artisans create a handcrafted wool felt miniature of your pet, capturing their unique markings and personality in every needle-felted detail.',
    longDescription: 'Using the ancient craft of needle felting, our artists spend 40-60 hours sculpting merino wool into a lifelike portrait of your pet. Working from your photographs, each fiber is carefully placed to recreate the exact coat pattern, the tilt of the ears, and that particular expression you know so well. The result is a tangible, soft-to-touch remembrance — a companion you can hold close.',
    price: 95,
    materials: ['Merino wool', 'Alpaca fiber blends', 'Glass eyes', 'Wire armature frame'],
    dimensions: '10-15cm height (customizable)',
    craftingTime: '4-6 weeks',
    features: [
      'Needle-felted from your photos',
      'Premium merino wool',
      'Custom pose available',
      'Comes with display stand',
      'Glass presentation dome included',
      'Progress photos during creation',
    ],
    images: ['/images/felt-01.jpg'],
    featured: true,
    isNew: false,
  },
  {
    id: 'candle-01',
    slug: 'memorial-candle-collection',
    name: 'Memorial Candle — Evening Light',
    category: 'candles',
    tagline: 'A gentle flame for quiet remembrance',
    description: 'Hand-poured soy wax candle infused with calming notes of chamomile, cedarwood, and vanilla — a ritual of light and memory.',
    longDescription: 'Created in collaboration with an artisanal fragrance house, our Memorial Candle is poured in small batches using 100% natural soy wax. The fragrance profile was designed to evoke the feeling of a quiet evening at home — chamomile for peace, cedarwood for grounding, and a whisper of vanilla for warmth. Each candle comes in a hand-thrown ceramic vessel that can be repurposed as a small keepsake holder after the candle has completed its 60-hour burn.',
    price: 18,
    materials: ['Natural soy wax', 'Essential oil blend', 'Hand-thrown ceramic vessel', 'Cotton wick'],
    dimensions: '8cm x 8cm x 8cm',
    craftingTime: '3-5 business days',
    features: [
      '60-hour burn time',
      'Natural essential oils',
      'Reusable ceramic vessel',
      'Hand-thrown by artisans',
      'Phthalate-free fragrance',
      'Beautiful gift packaging',
    ],
    images: ['/images/candle-01.jpg'],
    featured: true,
    isNew: true,
  },
  {
    id: 'card-01',
    slug: 'memorial-card-set',
    name: 'Hand-Lettered Memorial Card Set',
    category: 'cards',
    tagline: 'Words of love, set in ink and paper',
    description: 'A set of five hand-lettered memorial cards on cotton paper, each featuring a different sentiment for reflection and remembrance.',
    longDescription: 'Each card in this set is individually hand-lettered by our calligrapher using sumi ink on 100% cotton paper. The five sentiments — "Forever in our hearts," "The love remains," "A life well-loved," "Until we meet again," and "Gratitude for the journey" — offer different facets of the remembrance experience. The deckled edges and deckled edges add a tactile, handmade quality.',
    price: 12,
    materials: ['100% cotton paper', 'Sumi ink', 'Linen presentation envelope'],
    dimensions: 'A6 (10.5cm x 14.8cm)',
    craftingTime: '3-5 business days',
    features: [
      'Hand-lettered design',
      'Cotton paper with deckled edges',
      'Set of 5 cards',
      'Linen envelope included',
      'Archival-quality materials',
      'Suitable for framing',
    ],
    images: ['/images/card-01.jpg'],
    featured: false,
    isNew: false,
  },
  {
    id: 'photo-01',
    slug: 'pet-photo-card-set',
    name: 'Pet Photo Memorial Cards',
    category: 'photo-cards',
    tagline: 'Framed moments of joy, forever',
    description: 'Premium photo cards printed on fine art paper, designed to display your favorite photographs of your beloved companion.',
    longDescription: 'Transform your cherished photographs into archival-quality memorial prints. Each image is carefully color-corrected and printed on Hahnemühle fine art paper using pigment inks rated for 200+ years of fade resistance. The cards are presented in a linen-bound folio, creating an heirloom-quality keepsake that honors the visual story of your time together.',
    price: 22,
    materials: ['Hahnemühle fine art paper', 'Archival pigment inks', 'Linen folio presentation'],
    dimensions: 'A5 (14.8cm x 21cm)',
    craftingTime: '5-7 business days',
    features: [
      'Archival pigment printing',
      '200+ year fade resistance',
      'Linen presentation folio',
      'Set of 8 cards',
      'Custom photo selection',
      'Color correction included',
    ],
    images: ['/images/photo-01.jpg'],
    featured: false,
    isNew: false,
  },
  {
    id: 'gift-01',
    slug: 'ritual-memorial-gift-box',
    name: 'Ritual Memorial Gift Box',
    category: 'gift-boxes',
    tagline: 'A complete ceremony of remembrance',
    description: 'A thoughtfully curated gift box combining a memorial candle, hand-lettered cards, dried botanicals, and a personalized remembrance journal.',
    longDescription: 'Our Ritual Memorial Gift Box is designed as a complete ceremony — a way to honor your companion with intention. Inside the handcrafted wooden box, you will find: our signature Memorial Candle for a ritual of light, a set of hand-lettered cards for written reflection, a bundle of dried lavender and rosemary for scent memory, a beeswax-coated remembrance journal, and a small velvet pouch containing wildflower seeds to plant in their memory.',
    price: 55,
    materials: ['Handcrafted wooden box', 'Memorial candle', 'Cotton paper cards', 'Dried botanicals', 'Beeswax journal', 'Wildflower seeds'],
    dimensions: '25cm x 20cm x 8cm',
    craftingTime: '5-7 business days',
    features: [
      'Complete ritual experience',
      'Handcrafted wooden box',
      'Personalized journal',
      'Dried botanicals included',
      'Wildflower seeds for planting',
      'Elegant gift packaging',
    ],
    images: ['/images/gift-01.jpg'],
    featured: true,
    isNew: true,
  },
  {
    id: 'custom-01',
    slug: 'bespoke-remembrance-kit',
    name: 'Bespoke Remembrance Kit',
    category: 'remembrance-kits',
    tagline: 'A personal memorial, created together',
    description: 'Work with our artisans to create a fully customized remembrance experience — choose your combination of urn, candle, cards, and felt replica.',
    longDescription: 'For those seeking the most personal memorial, our Bespoke Remembrance Kit is a collaborative creation process. After an initial consultation, we pair you with a dedicated artisan who will guide you through each selection — the urn style and material, the candle fragrance profile, the card sentiments, and the wool felt portrait pose. Each kit is documented with process photographs and delivered in a custom-made presentation chest.',
    price: 180,
    materials: ['Custom-selected materials', 'Presentation chest', 'Process documentation'],
    dimensions: 'Custom',
    craftingTime: '6-8 weeks',
    features: [
      'Dedicated artisan consultation',
      'Fully customizable selection',
      'Process documentation',
      'Custom presentation chest',
      'Priority support',
      'Lifetime care guidance',
    ],
    images: ['/images/custom-01.jpg'],
    featured: false,
    isNew: false,
  },
];

export const faqs: FAQ[] = [
  {
    id: 'faq-01',
    question: 'How long does each product take to create?',
    answer: 'Each MementoPaws piece is handcrafted to order. Our hand-painted urns take 10-14 business days, wool felt replicas require 4-6 weeks due to the intricate needle-felting process, and curated gift boxes typically ship within 5-7 business days. You will find specific timing on each product page.',
    category: 'products',
  },
  {
    id: 'faq-02',
    question: 'Can I personalize or customize my order?',
    answer: 'Absolutely. Every MementoPaws piece can be personalized with your pet\'s name. For wool felt replicas, you provide the photographs and we work from them to capture your companion\'s unique markings and personality. Our Bespoke Remembrance Kit offers the highest level of customization, with a dedicated artisan guiding you through each selection.',
    category: 'custom',
  },
  {
    id: 'faq-03',
    question: 'What materials do you use for the urns?',
    answer: 'Our urns are crafted from premium ceramic clay and sustainably sourced walnut wood. Ceramic urns are hand-glazed with natural mineral pigments and accented with gold leaf. Walnut urns are carved from single blocks of North American black walnut, finished with organic beeswax. All materials are chosen for their beauty, durability, and respect for the natural world.',
    category: 'products',
  },
  {
    id: 'faq-04',
    question: 'How should I care for my MementoPaws piece?',
    answer: 'Each piece comes with detailed care instructions. Generally, ceramic urns should be kept away from direct sunlight and cleaned with a soft, dry cloth. Walnut wood pieces benefit from occasional beeswax conditioning (every 6-12 months). Wool felt replicas should be displayed under their glass dome and gently dusted. Memorial candles are designed for ritual use — we recommend lighting them during quiet moments of remembrance.',
    category: 'general',
  },
  {
    id: 'faq-05',
    question: 'Do you ship internationally?',
    answer: 'Yes, we ship worldwide. All orders are carefully packaged with protective materials to ensure your piece arrives safely. International shipping times vary by destination, typically 7-14 business days after the crafting period. Shipping costs are calculated at checkout based on your location and the weight of your order.',
    category: 'shipping',
  },
  {
    id: 'faq-06',
    question: 'What is your return policy?',
    answer: 'Due to the deeply personal and handcrafted nature of our pieces, we do not accept returns on custom or personalized items. For non-customized pieces, we accept returns within 14 days of delivery in original, unused condition. If your piece arrives damaged, please contact us within 48 hours with photographs, and we will arrange a replacement or refund.',
    category: 'ordering',
  },
  {
    id: 'faq-07',
    question: 'How do I send photos for a wool felt replica?',
    answer: 'After placing your order, you will receive an email with a secure upload link. We ask for 5-10 clear photographs of your pet from different angles, including close-ups of the face and full-body shots. Our artisans will review the images and may reach out for additional reference if needed. You will receive progress updates throughout the creation process.',
    category: 'custom',
  },
  {
    id: 'faq-08',
    question: 'Can I order a gift for someone who has lost their pet?',
    answer: 'Yes, a MementoPaws piece is a deeply meaningful gift. Our Ritual Memorial Gift Box was specifically designed for this purpose — it is a complete ceremony of remembrance that requires no customization. If you wish to gift a personalized urn or wool felt replica, we recommend coordinating with the recipient, as we will need their photographs and preferences.',
    category: 'ordering',
  },
];

export const testimonials: Testimonial[] = [
  {
    id: 'test-01',
    name: 'Sarah Mitchell',
    petName: 'Luna',
    petType: 'Golden Retriever',
    content: 'When I received the hand-painted urn for Luna, I cried — not from sadness alone, but from the beauty of it. The artisan captured her gentle spirit in every brushstroke. I keep it on my writing desk, and every morning I touch it and feel her presence. It is not an urn; it is a bridge between us.',
    productName: 'Hand-Painted Ceramic Urn',
    location: 'Portland, Oregon',
  },
  {
    id: 'test-02',
    name: 'James Chen',
    petName: 'Mochi',
    petType: 'Shiba Inu',
    content: 'The wool felt replica of Mochi sits on my bookshelf, and guests often mistake it for a living creature at first glance. The attention to detail — the exact curve of his tail, the white patch on his chest — is astonishing. When I miss him, I hold it, and the softness of the wool feels like comfort.',
    productName: 'Custom Wool Felt Replica',
    location: 'San Francisco, California',
  },
  {
    id: 'test-03',
    name: 'Emma & David Park',
    petName: 'Oliver',
    petType: 'British Shorthair',
    content: 'We ordered the Ritual Memorial Gift Box after losing Oliver, our cat of 17 years. Lighting the candle and writing in the journal together became a healing ritual we did every evening for weeks. The wildflower seeds have now bloomed in our garden. Thank you for creating a space for our grief to transform into gratitude.',
    productName: 'Ritual Memorial Gift Box',
    location: 'Brooklyn, New York',
  },
];

export const teamMembers: TeamMember[] = [
  {
    name: 'Yuki Tanaka',
    role: 'Founder & Lead Artisan',
    bio: 'Trained in traditional Japanese ceramics in Kyoto, Yuki founded MementoPaws after losing her own companion of 14 years. She brings the philosophy of kintsugi — finding beauty in what has been broken — to every piece the studio creates.',
    image: '/images/team-yuki.jpg',
  },
  {
    name: 'Marco Bellini',
    role: 'Master Woodworker',
    bio: 'A third-generation woodworker from Tuscany, Marco brings an Italian sensibility for form and material to our walnut collection. His pieces are studies in restraint — every detail serves a purpose, and nothing is added that does not honor the memory within.',
    image: '/images/team-marco.jpg',
  },
  {
    name: 'Lin Wei',
    role: 'Wool Felt Artist',
    bio: 'Lin discovered needle felting while recovering from an illness, finding in the rhythmic process a form of meditation. She brings extraordinary patience and emotional intuition to each portrait, often spending 50+ hours on a single piece.',
    image: '/images/team-lin.jpg',
  },
];

export const categories = [
  { id: 'urns', name: 'Memorial Urns', description: 'Handcrafted resting places of quiet beauty', image: '/images/cat-urns.jpg' },
  { id: 'felt-replicas', name: 'Wool Felt Replicas', description: 'Your companion, reimagined in wool', image: '/images/cat-felt.jpg' },
  { id: 'candles', name: 'Memorial Candles', description: 'A gentle flame for quiet remembrance', image: '/images/cat-candles.jpg' },
  { id: 'cards', name: 'Memorial Cards', description: 'Words of love, set in ink and paper', image: '/images/cat-cards.jpg' },
  { id: 'gift-boxes', name: 'Gift Boxes', description: 'Curated ceremonies of remembrance', image: '/images/cat-gift.jpg' },
];

export const brandStory = {
  title: 'Memory, Made Tangible',
  subtitle: 'We believe that love does not end with goodbye. It transforms, settles, and asks only to be honored.',
  paragraphs: [
    'MementoPaws was born from a personal loss — the quieting of a heartbeat that had been a constant companion for 14 years. In the search for a vessel worthy of those memories, our founder discovered a void: the market offered either cold, clinical containers or mass-produced trinkets. Neither felt like a home for love.',
    'Drawing from the Japanese philosophy of kintsugi — the art of repairing broken pottery with gold, making the cracks part of the object\'s history rather than something to hide — we began creating pieces that honor the beauty of what remains. Each MementoPaws piece is a collaboration between artisan and memory, crafted with the understanding that what we are holding is not just material, but meaning.',
    'Today, our small studio brings together ceramicists, woodworkers, fiber artists, and calligraphers who share a single conviction: that the objects we create in remembrance should be as beautiful as the love they honor. We work slowly, deliberately, and always with the awareness that each piece will become part of someone\'s private ritual of love and loss.',
  ],
};

export const craftingStepsByCategory: Record<string, { title: string; intro: string; steps: CraftingStep[] }> = {
  urns: {
    title: 'Twelve Steps to Eternity',
    intro: 'Each urn passes through 12 distinct stages over 72 hours. No two pieces emerge identical — every brushstroke, every glaze reaction, is a quiet collaboration between the artisan and the fire.',
    steps: [
      { num: '01', title: 'Clay Selection', desc: 'Premium ceramic clay sourced from Kyoto, selected for its fine grain and warm ivory undertone.' },
      { num: '02', title: 'Hand Shaping', desc: 'Each urn is thrown by hand on a potter\'s wheel over 6 hours, giving every piece its unique form.' },
      { num: '03', title: 'First Firing', desc: 'Bisque-fired at 980°C for 12 hours to harden the clay body and prepare it for glazing.' },
      { num: '04', title: 'Hand Painting', desc: 'Natural mineral pigments are applied by brush — botanical motifs inspired by the Japanese tradition of kintsugi.' },
      { num: '05', title: 'Gold Leaf', desc: '23-karat gold leaf is applied by hand to accent the painted motifs, symbolizing the beauty in what endures.' },
      { num: '06', title: 'Glaze Firing', desc: 'Three rounds of hand-glazing and kiln-firing at 1,240°C create the signature luminous finish.' },
      { num: '07', title: 'Interior Lining', desc: 'The interior is lined with midnight-blue velvet, hand-cut and fitted to create a soft resting chamber.' },
      { num: '08', title: 'Final Inspection', desc: 'Each piece is examined under natural light for 30 minutes before it is approved for delivery.' },
    ],
  },
  'felt-replicas': {
    title: 'From Photograph to Portrait',
    intro: 'Each wool felt replica requires 40–60 hours of focused needle-felting. Our artists work from your photographs, recreating every marking, every expression, every detail that made your companion unique.',
    steps: [
      { num: '01', title: 'Photo Study', desc: 'The artist studies 5–10 photographs of your companion, noting coat patterns, ear shapes, and signature expressions.' },
      { num: '02', title: 'Wire Armature', desc: 'A poseable wire frame is sculpted to match your companion\'s proportions and preferred stance.' },
      { num: '03', title: 'Core Felting', desc: 'Core wool is needle-felted onto the armature to build the body form — this is the structural foundation.' },
      { num: '04', title: 'Coat Layering', desc: 'Colored merino wool is applied in thin layers, matching the exact coat pattern from your photographs.' },
      { num: '05', title: 'Facial Detailing', desc: 'The face receives the most attention — eyes, nose, and mouth are shaped with surgical precision over 10+ hours.' },
      { num: '06', title: 'Texture Work', desc: 'Surface texture is added to replicate fur length, curl, and direction — the piece comes alive at this stage.' },
      { num: '07', title: 'Glass Eyes', desc: 'Hand-painted glass eyes are set into the felt, giving the portrait its lifelike gaze.' },
      { num: '08', title: 'Final Grooming', desc: 'The entire piece is gently brushed and trimmed, mounted on a display stand, and sealed under a glass dome.' },
    ],
  },
  candles: {
    title: 'A Ritual in Wax and Fragrance',
    intro: 'Our memorial candles are hand-poured in small batches using 100% natural soy wax and essential oils. Each vessel is hand-thrown by a ceramicist, making it a keepsake long after the flame has gone.',
    steps: [
      { num: '01', title: 'Vessel Throwing', desc: 'A ceramicist throws the vessel by hand, shaping the clay into a form that feels right in two hands.' },
      { num: '02', title: 'Fragrance Design', desc: 'Essential oils — chamomile, cedarwood, vanilla — are measured and blended to create a calm, grounding scent.' },
      { num: '03', title: 'Wax Melting', desc: '100% natural soy wax is slowly melted to precisely 82°C, ensuring even fragrance distribution.' },
      { num: '04', title: 'Pouring', desc: 'The wax-fragrance blend is hand-poured into the ceramic vessel at 57°C for optimal adhesion.' },
      { num: '05', title: 'Wick Setting', desc: 'A cotton wick is centered and secured as the wax cools over 24 hours.' },
      { num: '06', title: 'Curing', desc: 'The candle cures for 7 days, allowing the fragrance to fully develop before it is ready to burn.' },
      { num: '07', title: 'Surface Finish', desc: 'The wax surface is leveled by hand, and the vessel exterior receives a final polish.' },
      { num: '08', title: 'Gift Wrapping', desc: 'Each candle is wrapped in tissue, boxed, and accompanied by a card explaining the fragrance story.' },
    ],
  },
  'gift-boxes': {
    title: 'A Ceremony in a Box',
    intro: 'Each Ritual Memorial Gift Box is assembled by hand — a complete ceremony of remembrance designed to guide you through a quiet, personal ritual of love and loss.',
    steps: [
      { num: '01', title: 'Box Crafting', desc: 'A wooden box is handcrafted from sustainably sourced timber, sanded smooth, and finished with natural oil.' },
      { num: '02', title: 'Candle Selection', desc: 'A Memorial Candle in the recipient\'s chosen fragrance is placed as the centerpiece of the ritual.' },
      { num: '03', title: 'Card Lettering', desc: 'A set of hand-lettered memorial cards is selected, each bearing a different sentiment for reflection.' },
      { num: '04', title: 'Botanical Curation', desc: 'Dried lavender and rosemary are bundled by hand — chosen for their scent memory qualities.' },
      { num: '05', title: 'Journal Binding', desc: 'A beeswax-coated remembrance journal is hand-bound, its pages blank and waiting for words.' },
      { num: '06', title: 'Seed Pouch', desc: 'A velvet pouch of wildflower seeds is included — to plant in their memory and watch life return.' },
      { num: '07', title: 'Arrangement', desc: 'Each item is placed in the box with intention, creating a visual composition that feels like an offering.' },
      { num: '08', title: 'Sealing & Shipping', desc: 'The box is sealed with a wax stamp, wrapped in kraft paper, and shipped with care instructions.' },
    ],
  },
  default: {
    title: 'Handcrafted with Intention',
    intro: 'Every MementoPaws piece is made to order by our artisans — created with patience, precision, and the understanding that what we make carries meaning.',
    steps: [
      { num: '01', title: 'Consultation', desc: 'We begin by understanding your vision — the memory you wish to honor, and how you want to honor it.' },
      { num: '02', title: 'Material Selection', desc: 'Only the finest materials are chosen — each selected for its beauty, integrity, and emotional resonance.' },
      { num: '03', title: 'Handcrafting', desc: 'Our artisans work slowly and deliberately, giving each piece the time it needs to become what it must be.' },
      { num: '04', title: 'Quality Review', desc: 'Every piece is examined under natural light for imperfections — only the flawless continues forward.' },
      { num: '05', title: 'Finishing', desc: 'Final touches are applied by hand — a polish, a seal, a last brushstroke — before the piece is complete.' },
      { num: '06', title: 'Packaging', desc: 'Your piece is wrapped in protective, elegant packaging — ready for its journey to your home.' },
      { num: '07', title: 'Photography', desc: 'We photograph the finished piece and share the images with you before dispatch.' },
      { num: '08', title: 'Delivery', desc: 'Your memorial ships with care, arriving ready to become part of your quiet ritual of remembrance.' },
    ],
  },
};

export function getCraftingSteps(category: string) {
  return craftingStepsByCategory[category] || craftingStepsByCategory.default;
}

export function generateProductJsonLd(product: Product): Record<string, unknown> {
  return {
    '@context': 'https://schema.org',
    '@type': 'Product',
    name: product.name,
    description: product.description,
    category: product.category,
    offers: {
      '@type': 'Offer',
      price: product.price,
      priceCurrency: 'USD',
      availability: 'https://schema.org/MadeToOrder',
    },
    brand: {
      '@type': 'Brand',
      name: 'MementoPaws',
    },
  };
}
